language: java
matrix:
  include:
  - os: linux
    dist: trusty
  - os: osx
    osx_image: xcode11.3

jdk:
  - openjdk11

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:

# Build Robot
- cd InfiniteRecharge
- ls
- "./gradlew build"
